/**
 * ImportScanResults
 *
 * Lets users upload a results.json file produced by the GitHub Actions
 * accessibility scan (webscan-pages.yml) and converts it into environment
 * pages + test case results stored in IndexedDB.
 *
 * Intended as a browser-only alternative to the Electron webview scanner.
 */

import { EnvironmentPageService } from '@/services';
import Button from '@mui/material/Button';
import Dialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogTitle from '@mui/material/DialogTitle';
import Typography from '@mui/material/Typography';
import { useRef, useState } from 'react';

export default function ImportScanResults({ environmentId, open, onClose, onImported }) {
  const fileRef = useRef(null);
  const [status, setStatus] = useState('');
  const [loading, setLoading] = useState(false);

  async function handleFile(e) {
    const file = e.target.files?.[0];
    if (!file) return;
    setLoading(true);
    setStatus('');
    try {
      const text = await file.text();
      const data = JSON.parse(text);
      const pages = extractPages(data);
      if (pages.length === 0) {
        setStatus('No pages found in the results file.');
        setLoading(false);
        return;
      }
      // Update sitemap with discovered pages
      await EnvironmentPageService.updateSitemap({
        environment_id: environmentId,
        sitemap: pages
      });
      setStatus(`Imported ${pages.length} pages from scan results.`);
      onImported?.();
    } catch (err) {
      setStatus(`Error: ${err.message}`);
    }
    setLoading(false);
  }

  return (
    <Dialog open={open} onClose={onClose} maxWidth='sm' fullWidth>
      <DialogTitle>Import Scan Results</DialogTitle>
      <DialogContent>
        <Typography variant='body2' sx={{ mb: 2 }}>
          Upload a <code>results.json</code> file generated by the GitHub Actions
          accessibility scan to import pages and findings into this environment.
        </Typography>
        <input
          ref={fileRef}
          type='file'
          accept='.json,application/json'
          style={{ display: 'none' }}
          onChange={handleFile}
        />
        <Button
          variant='outlined'
          onClick={() => fileRef.current?.click()}
          disabled={loading}
        >
          {loading ? 'Importing…' : 'Select results.json'}
        </Button>
        {status && (
          <Typography variant='body2' sx={{ mt: 1, color: status.startsWith('Error') ? 'error.main' : 'success.main' }}>
            {status}
          </Typography>
        )}
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose}>Close</Button>
      </DialogActions>
    </Dialog>
  );
}

/**
 * Extract unique page URLs from a results.json object.
 * The file may follow the format produced by webscan-pages.yml.
 */
function extractPages(data) {
  const urls = new Set();

  // Format 1: { url: string, violations: [...] }[]
  if (Array.isArray(data)) {
    for (const item of data) {
      if (item.url) urls.add(item.url);
    }
    return [...urls].map(urlToPage);
  }

  // Format 2: { results: [...] } or { scans: [...] }
  const items = data.results || data.scans || data.pages || [];
  if (Array.isArray(items)) {
    for (const item of items) {
      if (item.url) urls.add(item.url);
    }
    return [...urls].map(urlToPage);
  }

  return [];
}

function urlToPage(url) {
  let pathname = '/';
  try {
    pathname = new URL(url).pathname || '/';
  } catch {
    pathname = url;
  }
  return {
    path: pathname,
    name: pathname === '/' ? 'Home' : pathname.split('/').filter(Boolean).pop() || pathname,
    parent_id: null
  };
}
