import db, { newId, nowIso } from './db/index';
import { applyPaginate, applySearch } from './core';

const STATUSES = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  CLOSED: 'CLOSED'
};

class EnvironmentTestService {
  static async find(input = {}, opt = {}) {
    if (input.id) return this.read({ id: input.id });
    let records = await db.environmentTests.toArray();
    if (input.environment_id) records = records.filter(r => r.environment_id === input.environment_id);
    if (input.search) records = applySearch(records, 'name', input.search);
    return applyPaginate(records, input);
  }

  static async read(input = {}) {
    const test = await db.environmentTests.get(input.id);
    if (!test) return null;
    const env = test.environment_id ? await db.environments.get(test.environment_id) : null;
    return { ...test, environment: env || null };
  }

  static async create(input = {}) {
    const id = newId();
    const record = {
      id,
      name: input.name,
      environment_id: input.environment_id,
      functionality_note: input.functionality_note || '',
      page_variety_note: input.page_variety_note || '',
      status: STATUSES.OPEN,
      start_date: input.start_date || nowIso(),
      end_date: null,
      created_at: nowIso(),
      updated_at: nowIso()
    };
    await db.environmentTests.add(record);
    return this.read({ id });
  }

  static async update(input = {}) {
    const test = await db.environmentTests.get(input.id);
    if (!test) throw new Error('Test not found');
    const updates = { updated_at: nowIso() };
    if (input.name !== undefined) updates.name = input.name;
    if (input.functionality_note !== undefined) updates.functionality_note = input.functionality_note;
    if (input.page_variety_note !== undefined) updates.page_variety_note = input.page_variety_note;
    if (input.status !== undefined) updates.status = input.status;
    if (input.end_date !== undefined) updates.end_date = input.end_date;
    await db.environmentTests.update(input.id, updates);
    return this.read({ id: input.id });
  }

  static async startTest(input = {}) {
    // In browser: mark test as in-progress and create EnvironmentTestPage rows for each page in the sitemap
    const test = await db.environmentTests.get(input.id);
    if (!test) throw new Error('Test not found');
    await db.environmentTests.update(input.id, { status: STATUSES.IN_PROGRESS, updated_at: nowIso() });
    const pages = await db.environmentPages.where('environment_id').equals(test.environment_id).toArray();
    for (const page of pages) {
      const existing = await db.environmentTestPages
        .where('environment_test_id').equals(input.id)
        .filter(r => r.environment_page_id === page.id)
        .first();
      if (!existing) {
        await db.environmentTestPages.add({
          id: newId(),
          environment_test_id: input.id,
          environment_page_id: page.id,
          start_date: nowIso(),
          end_date: null
        });
      }
    }
    return this.read({ id: input.id });
  }

  static async closeTest(input = {}) {
    await db.environmentTests.update(input.id, { status: STATUSES.CLOSED, end_date: nowIso(), updated_at: nowIso() });
    return this.read({ id: input.id });
  }

  static async openClosedTest(input = {}) {
    await db.environmentTests.update(input.id, { status: STATUSES.IN_PROGRESS, end_date: null, updated_at: nowIso() });
    return this.read({ id: input.id });
  }

  static async getSitemap(input = {}) {
    const test = await db.environmentTests.get(input.id);
    if (!test) return [];
    const pages = await db.environmentPages.where('environment_id').equals(test.environment_id).toArray();
    return pages;
  }

  static async getStats(input = {}) {
    const pages = await db.environmentTestPages.where('environment_test_id').equals(input.id).toArray();
    return { total: pages.length, tested: pages.filter(p => p.end_date).length };
  }

  static async generateReport() {
    // Not fully implemented in browser; report is generated by audit module
    return { success: false, message: 'Use the Audit module to generate reports' };
  }

  static async generateOccurrenceData() {
    return { success: false };
  }

  static async hasOccurrenceData() {
    return false;
  }

  static async addPage(input = {}) {
    const test = await db.environmentTests.get(input.environment_test_id);
    if (!test) throw new Error('Test not found');
    let page = await db.environmentPages.get(input.environment_page_id);
    if (!page) throw new Error('Page not found');
    const existing = await db.environmentTestPages
      .where('environment_test_id').equals(input.environment_test_id)
      .filter(r => r.environment_page_id === input.environment_page_id)
      .first();
    if (!existing) {
      await db.environmentTestPages.add({
        id: newId(),
        environment_test_id: input.environment_test_id,
        environment_page_id: input.environment_page_id,
        start_date: nowIso(),
        end_date: null
      });
    }
    return { success: true };
  }

  static async rescanSitemap() {
    // Web crawling is not available in browser
    return { success: false, message: 'Sitemap scanning is not available in the browser. Import scan results from GitHub Actions instead.' };
  }
}

export default EnvironmentTestService;
